Update index.html
htmlacademy-htmlcss/182213-device-32 pull request #2
Opened 2021-09-26 16:33 UTC by VSage22

2021-09-27 07:11 UTC, Dima-Dim requested changes
https://up.htmlacademy.ru/htmlcss/32/help/4.5
"Приступать к следующему заданию по тому же проекту не стоит, пока не будет принято предыдущее."
Давай с начала разберёмся с главной страницей, чтобы вторая уже была сделать с меньшим количеством ошибок.

2021-09-27 07:11 UTC, Dima-Dim commented on index.html
> +        <section id="delivery">
Тоже похоже на список.

2021-09-27 07:29 UTC, VSage22 commented on index.html
> +        <img class="page-header-logo" src="" alt="Логотип магазина Device">
Изначально вынесла его вверх, до начала навигации, но потом решила что с внутренних страниц при нажатии на логотип будет переход на главную страницу. Поняла, выношу на вверх.

2021-09-27 07:30 UTC, VSage22 commented on index.html
> +                  <button type="submit"><span class="visually-hidden">Поиск</span></button>
Возле поля вводя должна быть иконка Search, но пока мы иконки не добавляем, если это будет не кнопка то ссылка?

2021-09-27 07:31 UTC, VSage22 commented on index.html
> +              <div class="search-container">
Сейчас лучше удалить?

2021-09-27 07:38 UTC, VSage22 commented on index.html
> +            <a class="navigation-link" href="#">Войти</a>
На лайве нам рассказывали что это тоже главная навигация но с уточнение так сказать, их можно делать как navigation-user и в Демке так же. Сделать просто отдельным списком вне тега nav?

2021-09-27 07:43 UTC, Dima-Dim commented on index.html
> +                  <button type="submit"><span class="visually-hidden">Поиск</span></button>
Про то и речь. Когда она появится - решим что чем будет :)

2021-09-27 07:44 UTC, Dima-Dim commented on index.html
> +              <div class="search-container">
Да, когда потребуется - добавишь.

2021-09-27 07:45 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="#">Войти</a>
Я про то что это не то, что должно быть в теге nav, т.е. не является основной навигацией. Все навигации с уточнениями и говорками могут быть, а могу не быть скорее всего не для тега nav.

2021-09-27 07:48 UTC, VSage22 commented on index.html
> +                  <button type="submit"><span class="visually-hidden">Поиск</span></button>
Оставить только форму?

2021-09-27 07:50 UTC, Dima-Dim commented on index.html
> +                  <button type="submit"><span class="visually-hidden">Поиск</span></button>
Убрать button :)

2021-09-27 07:51 UTC, VSage22 commented on index.html
> +          <li class="navigation-item">
Но ведь контакты относятся к основному меню. Тогда если это не навигация вынесу, эти 3и пункта в отдельный список.

2021-09-27 07:53 UTC, VSage22 commented on index.html
> +          <h1>01</h1>
ой с заголовками у меня вообще проблема, Это будет просто <span>?

2021-09-27 12:45 UTC, VSage22 commented on index.html
> +            <a class="navigation-link" href="#">Войти</a>
Я не понимаю, я могу оставить эти пункты в меню или мне их необходимо вынести в отдельный div?

2021-09-28 15:10 UTC, Dima-Dim approved these changes

2021-09-28 15:10 UTC, merged

2021-09-28 15:11 UTC, Dima-Dim commented on index.html
> +          <h1>01</h1>
Как вариант.

2021-09-28 15:12 UTC, Dima-Dim commented on index.html
> +        <ul class="navigation-list navigation-user">
На данном этапе можно оставить просто ссылки, а если для стилизации понадобятся контейнреы, то их всегда можно будет добавить.

2021-09-28 15:14 UTC, Dima-Dim commented on index.html
> +            <a class="navigation-link" href="#">Войти</a>
Это не критичный момент, но лучше такое выносить за пределы nav и не размечаить списком.